### PR TITLE
Fix Github URL

### PR DESCRIPTION
**Pull request by ben-kaufman**
Fixed a few broken links which were directed to a previous GitHub account.

BTW, what is the status of this project? Is it under active development?

### CODE REVIEW

**Comment by ChristopherA** [comment]
It is under active development.

**Comment by ChristopherA** [comment]
These should all be fixed in PR #38 but with relative links — can you confirm so I can close?

/cc @Fonta1n3

**Comment by Fonta1n3** [comment]
Thanks for pointing that out, the PR submitted just prior to this alters the entire repo structure so the URL request URL would still be broken and this probably won't be able to get merged. Have updated the code manually, cheers. 

@ChristopherA I can confirm 👍

**Comment by ben-kaufman** [comment]
@ChristopherA @Fonta1n3 thanks for the response and for handling the issue. Closing this PR now.

**Pull request closed without merging**
